### ISSUE TITLE
Internal server error on Test app in SANDBOX environment

### ISSUE THREAD

**Issue by vishnutsatheesh** [cashfree/nextgen-android#3]
SQLiteDatabase: Error inserting source=android contexts={"app":{"app_identifier":"com.honebi.ratnadeep.test","app_name":"Ratnadeep - Test","app_version":"1.0 - test - 24112022","app_build":2,"type":"app"},"os":{"name":"Android","version":"10","build":"QPTS30.61-18-16-19","kernel_version":"4.4.192-perf+","rooted":false,"type":"os"},"device":{"name":"motorola one power","family":"motorola","model":"motorola one power","model_id":"QPTS30.61-18-16-19","orientation":"portrait","manufacturer":"motorola","brand":"motorola","screen_density":3,"screen_dpi":480,"screen_height_pixels":2016,"screen_width_pixels":1080,"id":"02871343-72e0-4a49-9694-220069f89e85","timezone":"Asia\/Calcutta","archs":["arm64-v8a","armeabi-v7a","armeabi"],"language":"en","locale":"en_US","type":"device"}} sdk_version=10100 environment=SANDBOX _id=rbcl1XGeMut7SJnLRf6s request_id=cmJjbDFYR2VNdXQ3U0puTFJmNnMrU0FOREJPWA== timestamp=1669273715743 release_version=com.cashfree.pg.core@1.1.0+10100
                                         android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: PAYMENT_EVENT.app_id (code 1299 SQLITE_CONSTRAINT_NOTNULL)
                                         	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                         	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
                                         	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
                                         	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
                                         	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
                                         	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
                                         	at com.cashfree.pg.cf_analytics.CFAnalyticsDatabase.lambda$addPaymentEvent$0$com-cashfree-pg-cf_analytics-CFAnalyticsDatabase(CFAnalyticsDatabase.java:48)
                                         	at com.cashfree.pg.cf_analytics.CFAnalyticsDatabase$$ExternalSyntheticLambda6.run(Unknown Source:4)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                         	at java.lang.Thread.run(Thread.java:919)

**Comment by viral-bandhu** [comment]
facing same issue with Android app

**Comment by vishnutsatheesh** [comment]
Just was trying to make the test payment by UPI, then i got it.

**Comment by arjun-cashfree** [comment]
Please update the SDK to version 1.1.4 if you are using order_token to invoke the SDK and to version 2.0.1 if you are using payment_session_id.
